In [ ]:
import torch

from torch.utils.data import DataLoader, ConcatDataset

In [2]:
from lstm_scratch import SimpleLSTM, test_model
from helpers import CVFConfigForGCNWSuccLSTMDataset

In [3]:
model = "lstm_trained_at_2025_04_07_18_35"

In [4]:
device = "cuda"

In [5]:
# Model class must be defined somewhere
model = torch.load(f"trained_models/{model}.pt", weights_only=False)
model.eval()

SimpleLSTM(
  (lstm): LSTM(3, 32, batch_first=True)
  (h2o): Linear(in_features=32, out_features=1, bias=True)
)

In [6]:
dataset = CVFConfigForGCNWSuccLSTMDataset(
    device,
    "star_graph_n7_config_rank_dataset.csv",
)

In [7]:
dataset_coll = ConcatDataset([dataset])

In [8]:
test_model(model, dataset_coll)

tensor([[[6.]]], device='cuda:0') tensor([[[1.1812]]], device='cuda:0')
tensor([[[5.]]], device='cuda:0') tensor([[[2.8799]]], device='cuda:0')
tensor([[[5.]]], device='cuda:0') tensor([[[2.5793]]], device='cuda:0')
tensor([[[4.]]], device='cuda:0') tensor([[[2.8586]]], device='cuda:0')
tensor([[[5.]]], device='cuda:0') tensor([[[2.5459]]], device='cuda:0')
tensor([[[4.]]], device='cuda:0') tensor([[[2.7746]]], device='cuda:0')
tensor([[[4.]]], device='cuda:0') tensor([[[2.5743]]], device='cuda:0')
tensor([[[3.]]], device='cuda:0') tensor([[[2.4501]]], device='cuda:0')
tensor([[[5.]]], device='cuda:0') tensor([[[2.5273]]], device='cuda:0')
tensor([[[4.]]], device='cuda:0') tensor([[[2.8157]]], device='cuda:0')
tensor([[[4.]]], device='cuda:0') tensor([[[2.6198]]], device='cuda:0')
tensor([[[3.]]], device='cuda:0') tensor([[[2.3662]]], device='cuda:0')
tensor([[[4.]]], device='cuda:0') tensor([[[2.4999]]], device='cuda:0')
tensor([[[3.]]], device='cuda:0') tensor([[[2.2803]]], device='c

Test set | MSE loss: 0.3459 | Total matched: 358 out of 448 (Accuracy: 79.91%)


tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]], device='cuda:0')
tensor([[[0.]]], device='cuda:0') tensor([[[0.]]