In [2]:
import torch

In [4]:
from torch_geometric.nn.pool import global_mean_pool

In [3]:
x = torch.tensor([[[0.0461],
         [0.0021],
         [0.0021],
         [0.0021]],
        [[0.0161],
         [0.0018],
         [0.0018],
         [0.0012]]]
)

In [9]:
y = global_mean_pool(x, torch.tensor([0, 0, 0, 0]))
y, y.shape

(tensor([[[0.0131]],
 
         [[0.0052]]]),
 torch.Size([2, 1, 1]))

In [8]:
x.shape

torch.Size([2, 4, 1])

In [23]:
global_mean_pool(x, torch.zeros(x.size(1)).to("cpu").long())

tensor([[[0.0131]],

        [[0.0052]]])

In [22]:
torch.zeros(x.size(1)).to("cpu").long()

tensor([0, 0, 0, 0])