In [8]:
import torch
import torch.nn.functional as F

In [9]:
from torch_geometric.nn.pool import global_mean_pool

In [10]:
x = torch.tensor([[[0.0461],
         [0.0021],
         [0.0021],
         [0.0021]],
        [[0.0161],
         [0.0018],
         [0.0018],
         [0.0012]]]
)

In [11]:
y = global_mean_pool(x, torch.tensor([0, 0, 0, 0]))
y, y.shape

(tensor([[[0.0131]],
 
         [[0.0052]]]),
 torch.Size([2, 1, 1]))

In [5]:
x.shape

torch.Size([2, 4, 1])

In [6]:
global_mean_pool(x, torch.zeros(x.size(1)).to("cpu").long())

tensor([[[0.0131]],

        [[0.0052]]])

In [7]:
torch.zeros(x.size(1)).to("cpu").long()

tensor([0, 0, 0, 0])

In [16]:
F.one_hot(torch.tensor([1, 2, 3]), num_classes=4)

tensor([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])