In [2]:
import torch
import torch.nn.functional as F

from torch_geometric.data import Data
from torch_geometric.nn import GCNConv
from torch_geometric.utils import to_dense_adj
from torch_geometric.nn import global_mean_pool as gap, global_max_pool as gmp

In [13]:
edge_index = torch.tensor([
    [0, 1],
    [0, 2],
    [0, 3],
    [1, 0],
    [2, 0],
    [3, 0]
], dtype=torch.long)

x = torch.tensor([[0, 0, 0, 0], [1, 1, 1, 1]], dtype=torch.float) # configs: [0, 0, 0, 0], [1, 1, 1, 1]

y = torch.tensor([[3.0], [1.0]]) # ranks

data = Data(x=x, edge_index=edge_index.t().contiguous(), y=y)

In [14]:
data.num_nodes, data.num_edges, data.num_node_features, data.has_isolated_nodes(), data.has_self_loops(), data.is_directed()

(2, 6, 4, False, False, True)

In [15]:
data.keys()

['edge_index', 'x', 'y']

In [16]:
adjacency = to_dense_adj(edge_index.t().contiguous())[0]

In [17]:
adjacency

tensor([[0., 1., 1., 1.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]])

In [24]:
data.x

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.]])

In [ ]:
class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(data.x.shape[0], 16)
        self.conv2 = GCNConv(16, 16)
        self.out = torch.nn.Linear(16, data.x.shape[0])

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        x = F.relu(x)
        x = gap(x, None)
        return self.out(x)

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = GCN().to(device)
data = data.to(device)
# data = dataset[0].to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)

model.train()
for epoch in range(200):
    optimizer.zero_grad()
    out = model(data)
    loss = F.mse_loss(out, data.y)
    print("Loss:", loss)
    loss.backward()
    optimizer.step()

RuntimeError: index 2 is out of bounds for dimension 0 with size 2

In [11]:
x = torch.tensor([[0, 1], [0, 1], [0, 1], [0, 1]], dtype=torch.float) # configs: [0, 0, 0, 0], [1, 1, 1, 1]

test_data = Data(x=x, edge_index=data.edge_index)

model(test_data)

tensor([[2.1558, 2.2071]], grad_fn=<AddmmBackward0>)

In [12]:
data.edge_index

tensor([[0, 0, 0, 1, 2, 3],
        [1, 2, 3, 0, 0, 0]])