In [1]:
import torch
import torch.nn.functional as F

from torch_geometric.data import Data
from torch.utils.data import DataLoader
from torch_geometric.utils import to_dense_adj

In [2]:
from helpers import CVFConfigDataset

In [3]:
class VanillaGNNLayer(torch.nn.Module):
    def __init__(self, dim_in, dim_out):
        super().__init__()
        self.linear = torch.nn.Linear(dim_in, dim_out, bias=False)

    def forward(self, x, adjacency):
        x = self.linear(x)
        # print(adjacency.shape, x.shape)
        # print(x)
        x = torch.sparse.mm(adjacency, x)
        return x

In [4]:
dataset = CVFConfigDataset()
data_loader = DataLoader(dataset, batch_size=1, shuffle=False)

In [5]:
edge_index = torch.tensor([
    [0, 1],
    [0, 2],
    [0, 3],
    [1, 0],
    [2, 0],
    [3, 0]
], dtype=torch.long)

# # x = torch.tensor([[0], [0], [0], [0]], dtype=torch.float) # configs: [0, 0, 0, 0], [1, 1, 1, 1]
# x = torch.tensor([[0, 1], [0, 1], [0, 1], [0, 1]], dtype=torch.float) # configs: [0, 0, 0, 0], [1, 1, 1, 1]

# y = torch.tensor([[3.0, 1.0]]) # ranks

# data = Data(x=x, edge_index=edge_index.t().contiguous(), y=y)
# data.train_mask = torch.tensor([1 for _ in range(len(x))])

In [6]:
adjacency = to_dense_adj(edge_index.t().contiguous())[0]
adjacency += torch.eye(len(adjacency))
adjacency

tensor([[1., 1., 1., 1.],
        [1., 1., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 0., 1.]])

In [32]:
class VanillaGNN(torch.nn.Module):
    def __init__(self, dim_in, dim_h, dim_out):
        super().__init__()
        self.gnn1 = VanillaGNNLayer(dim_in, dim_h)
        self.gnn2 = VanillaGNNLayer(dim_h, dim_out)
        # self.out = torch.nn.Linear(dim_h, dim_out)
    
    def forward(self, x, adjacency):
        h = self.gnn1(x, adjacency)
        h = torch.relu(h)
        h = self.gnn2(h, adjacency)
        h = torch.relu(h)
        # h = self.out(h)
        # print(torch.relu(h))
        return F.softmax(h, dim=1)
    
    def fit(self, data_loader, epochs):
        # criterion = torch.nn.MSELoss()
        criterion = torch.nn.CrossEntropyLoss()
        optimizer = torch.optim.Adam(self.parameters(), lr=0.01, weight_decay=5e-4)
        self.train()
        for epoch in range(epochs+1):
            for batch in data_loader:
                x = batch[0][0]
                y = torch.zeros(4, 1)
                y[batch[1]] = 1
                optimizer.zero_grad()
                out = self(x, adjacency)
                print(out, y)
                loss = criterion(out, y)
                loss.backward()
                optimizer.step()
            
            # if loss < 0.009:
            #     print("Loss threshold met.")
            #     break
            print("Loss:", loss)


In [33]:
gnn = VanillaGNN(1, 32, 1)
print(gnn)
gnn.fit(data_loader, epochs=50)

VanillaGNN(
  (gnn1): VanillaGNNLayer(
    (linear): Linear(in_features=1, out_features=32, bias=False)
  )
  (gnn2): VanillaGNNLayer(
    (linear): Linear(in_features=32, out_features=1, bias=False)
  )
)
tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>) tensor([[0.],
        [0.],
        [0.],
        [1.]])
tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>) tensor([[0.],
        [0.],
        [1.],
        [0.]])
tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>) tensor([[0.],
        [0.],
        [1.],
        [0.]])
tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>) tensor([[0.],
        [1.],
        [0.],
        [0.]])
tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>) tensor([[0.],
        [0.],
        [1.],
        [0.]])
tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)

In [34]:
out = gnn(torch.tensor([[0.], [1.], [1.], [1.]]), adjacency)
print(out)

tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SoftmaxBackward0>)
