In [29]:
import numpy as np

# Adjacency matrix
A = np.array([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 0],
    [0, 1, 0, 0]
])

N = 8
A = np.random.randint(0, N, (N, N))
print(A)

# Degree matrix
D = np.diag(np.sum(A, axis=1))

# Laplacian matrix
L = D - A

# Eigen decomposition
eigenvalues, eigenvectors = np.linalg.eigh(L)  # eigh is for symmetric matrices like Laplacian

# Print the sorted eigenvalues
print("Eigenvalues:", eigenvalues)

# Choose k=2 (skip the first eigenvector)
k = 1
embedding = eigenvectors[:, 1:1+k]  # Take eigenvectors corresponding to the 2 smallest non-zero eigenvalues

print("Spectral Embedding (2D):")
print(embedding)


[[7 7 2 1 4 4 2 0]
 [4 7 5 4 1 0 3 5]
 [7 5 2 0 5 0 4 5]
 [4 7 0 2 0 0 1 5]
 [1 6 5 1 7 2 4 6]
 [4 2 5 2 4 5 5 7]
 [0 2 2 2 7 6 1 2]
 [5 7 6 3 6 5 3 3]]
Eigenvalues: [-3.79062481 16.18405886 18.86440067 24.75271941 31.68221722 32.71165587
 34.29115918 40.3044136 ]
Spectral Embedding (2D):
[[-0.28580238]
 [-0.18965641]
 [ 0.12291452]
 [-0.64756382]
 [ 0.36838383]
 [ 0.202934  ]
 [ 0.51876299]
 [ 0.04355088]]


In [34]:
import numpy as np
from sklearn.manifold import SpectralEmbedding

# Adjacency matrix (4-node example)
A = np.array([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 0],
    [0, 1, 0, 0]
])

# Create Spectral Embedding model
embedding_model = SpectralEmbedding(n_components=1, affinity='precomputed')

# Fit and transform
embedding = embedding_model.fit_transform(A)

print("Spectral Embedding:")
print(embedding.T)

Spectral Embedding:
[[ 0.28867513 -0.28867513  0.57735027 -0.57735027]]
