In [2]:
import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GATv2Conv

# Create a simple graph data
# Let's assume a graph with 4 nodes, and the following edge connections:
# 0 - 1, 1 - 2, 2 - 3, 3 - 0
# Node features: 4 nodes, each with 3 features
# Edge indices: 4 edges (each connects two nodes)

# Edge index: shape [2, num_edges], representing edge connections
edge_index = torch.tensor([[0, 1, 2, 3],
                           [1, 2, 3, 0]], dtype=torch.long)

# Node features: 4 nodes, each with 3 features
x = torch.tensor([[1, 2, 3],  # Node 0
                  [4, 5, 6],  # Node 1
                  [7, 8, 9],  # Node 2
                  [10, 11, 12]], dtype=torch.float)

# Create a graph data object
data = Data(x=x, edge_index=edge_index)

# Define a GATv2 model with two layers and 8 attention heads
class GATv2(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads):
        super(GATv2, self).__init__()
        # First GATv2 layer with 8 attention heads
        self.gatv2_1 = GATv2Conv(in_channels, hidden_channels, heads=heads)  # 8 attention heads
        # Second GATv2 layer with 8 attention heads
        self.gatv2_2 = GATv2Conv(hidden_channels * heads, out_channels, heads=1)  # 1 attention head
    
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        # First layer of GATv2
        x = self.gatv2_1(x, edge_index)  # Apply first GATv2Conv layer
        x = F.relu(x)  # Apply ReLU activation
        # Second layer of GATv2
        x = self.gatv2_2(x, edge_index)  # Apply second GATv2Conv layer
        return F.relu(x)  # Apply ReLU activation after second layer

# Instantiate the GATv2 model with 3 input features, 4 hidden features, and 2 output features
model = GATv2(in_channels=3, hidden_channels=4, out_channels=2, heads=8)

# Forward pass
out = model(data)
print(out)


tensor([[0.8772, 4.8757],
        [0.6484, 1.6767],
        [0.6600, 1.7931],
        [0.8126, 3.6130]], grad_fn=<ReluBackward0>)


In [7]:
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GATv2Conv
import torch.nn.functional as F

# Sample graph data (replace with your own dataset)
# Graph 1
x1 = torch.tensor([[1, 2], [2, 3], [3, 4]], dtype=torch.float)  # Node features
edge_index1 = torch.tensor([[0, 1, 1], [1, 2, 0]], dtype=torch.long)  # Edge indices

# Graph 2
x2 = torch.tensor([[4, 5], [5, 6], [6, 7]], dtype=torch.float)  # Node features
edge_index2 = torch.tensor([[0, 1, 1], [1, 2, 0]], dtype=torch.long)  # Edge indices

# Create Data objects for each graph
data1 = Data(x=x1, edge_index=edge_index1)
data2 = Data(x=x2, edge_index=edge_index2)

# Create a DataLoader for batching
dataset = [data1, data2]
loader = DataLoader(dataset, batch_size=2, shuffle=False)

# Define the GATv2 model
class GATv2Model(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(GATv2Model, self).__init__()
        self.gatv2 = GATv2Conv(in_channels, out_channels, heads=1, concat=False)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.gatv2(x, edge_index)
        return x

# Instantiate model and optimizer
model = GATv2Model(in_channels=2, out_channels=2)  # Example input features are 2-dimensional
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    model.train()
    total_loss = 0
    for data in loader:  # Data is a batch of graphs
        print(data.x.shape)
        optimizer.zero_grad()
        
        # Forward pass
        out = model(data)
        
        # # Dummy target for demonstration
        # target = torch.tensor([1, 0], dtype=torch.long).to(out.device)  # Example targets for the batch
        
        # # Compute loss (using cross-entropy for classification example)
        # loss = F.cross_entropy(out, target)
        # total_loss += loss.item()
        
        # # Backward pass
        # loss.backward()
        # optimizer.step()""
    
    print(f"Epoch {epoch+1}, Loss: {total_loss}")

torch.Size([6, 2])
Epoch 1, Loss: 0
torch.Size([6, 2])
Epoch 2, Loss: 0
torch.Size([6, 2])
Epoch 3, Loss: 0
torch.Size([6, 2])
Epoch 4, Loss: 0
torch.Size([6, 2])
Epoch 5, Loss: 0
torch.Size([6, 2])
Epoch 6, Loss: 0
torch.Size([6, 2])
Epoch 7, Loss: 0
torch.Size([6, 2])
Epoch 8, Loss: 0
torch.Size([6, 2])
Epoch 9, Loss: 0
torch.Size([6, 2])
Epoch 10, Loss: 0
torch.Size([6, 2])
Epoch 11, Loss: 0
torch.Size([6, 2])
Epoch 12, Loss: 0
torch.Size([6, 2])
Epoch 13, Loss: 0
torch.Size([6, 2])
Epoch 14, Loss: 0
torch.Size([6, 2])
Epoch 15, Loss: 0
torch.Size([6, 2])
Epoch 16, Loss: 0
torch.Size([6, 2])
Epoch 17, Loss: 0
torch.Size([6, 2])
Epoch 18, Loss: 0
torch.Size([6, 2])
Epoch 19, Loss: 0
torch.Size([6, 2])
Epoch 20, Loss: 0
torch.Size([6, 2])
Epoch 21, Loss: 0
torch.Size([6, 2])
Epoch 22, Loss: 0
torch.Size([6, 2])
Epoch 23, Loss: 0
torch.Size([6, 2])
Epoch 24, Loss: 0
torch.Size([6, 2])
Epoch 25, Loss: 0
torch.Size([6, 2])
Epoch 26, Loss: 0
torch.Size([6, 2])
Epoch 27, Loss: 0
torch.Size

/home/agaru/anaconda3/envs/cvf/lib/python3.12/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [ ]:
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GATv2Conv
import torch.nn.functional as F

# Example graph data
# Graph 1
x1 = torch.tensor([[[1, 0, 0], [1, 1, 1], [0, 0, 1]]], dtype=torch.float)  # Node features for graph 1
edge_index1 = torch.tensor([[0, 1, 1], [1, 2, 0]], dtype=torch.long)  # Edge indices for graph 1

# Graph 2
x2 = torch.tensor([[[0, 1, 0], [1, 0, 1], [1, 1, 0]]], dtype=torch.float)  # Node features for graph 2
edge_index2 = torch.tensor([[0, 1, 1], [1, 2, 0]], dtype=torch.long)  # Edge indices for graph 2

# Create Data objects for each graph
data1 = Data(x=x1, edge_index=edge_index1)
data2 = Data(x=x2, edge_index=edge_index2)

# Create a DataLoader for batching
dataset = [data1, data2]
loader = DataLoader(dataset, batch_size=2, shuffle=False)

# Define the GATv2 model
class GATv2Model(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(GATv2Model, self).__init__()
        # self.linear1 = torch.Linear(in_channels, )
        self.gatv2 = GATv2Conv(in_channels, out_channels, heads=1, concat=False)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        # If the input is 3D (batch_size, num_nodes, in_channels), flatten it
        print(x)
        print('here...')
        if x.dim() == 3:
            print('there...')
            x = x.view(-1, x.size(-1))  # Flatten to 2D: (total_num_nodes_in_batch, in_channels)
            print(x)
            # print(x.squeeze(0).shape)
        x = self.gatv2(x, edge_index)
        return x

# Instantiate model and optimizer
model = GATv2Model(in_channels=2, out_channels=2)  # Example input features are 2-dimensional
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(100):
    model.train()
    total_loss = 0
    for data in loader:  # Data is a batch of graphs
        print(data.x.shape)
        optimizer.zero_grad()
        
        # Forward pass
        out = model(data)
        
    #     # Dummy target for demonstration (replace with actual target)
    #     target = torch.tensor([1, 0], dtype=torch.long).to(out.device)  # Example targets for the batch
        
    #     # Compute loss (using cross-entropy for classification example)
    #     loss = F.cross_entropy(out, target)
    #     total_loss += loss.item()
        
    #     # Backward pass
    #     loss.backward()
    #     optimizer.step()
    
    # print(f"Epoch {epoch+1}, Loss: {total_loss}")


torch.Size([2, 3, 3])
tensor([[[1., 0., 0.],
         [1., 1., 1.],
         [0., 0., 1.]],

        [[0., 1., 0.],
         [1., 0., 1.],
         [1., 1., 0.]]])
here...
there...
tensor([[1., 0., 0.],
        [1., 1., 1.],
        [0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 1.],
        [1., 1., 0.]])


/home/agaru/anaconda3/envs/cvf/lib/python3.12/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (6x3 and 2x2)

In [11]:
import torch
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GATv2Conv

# Define the graph data for one batch
# Example batch of graphs: One graph with 3 nodes
node_features_batch = [
    torch.tensor([[1, 0, 0], [1, 1, 1], [0, 0, 1]], dtype=torch.float)  # Node features for a graph
]
edge_index_batch = [
    torch.tensor([[0, 1, 1], [1, 2, 0]], dtype=torch.long)  # Edge index for the same graph
]

# Wrap each graph into a PyTorch Geometric Data object
graph_batch = [
    Data(x=node_features, edge_index=edge_index)
    for node_features, edge_index in zip(node_features_batch, edge_index_batch)
]

# Use DataLoader for batching multiple graphs (expand if you have more than one graph)
data_loader = DataLoader(graph_batch, batch_size=1, shuffle=True)

# Define GATv2-based model
class GATv2Model(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, heads=2):
        super(GATv2Model, self).__init__()
        # First GATv2Conv layer
        self.gatv2_1 = GATv2Conv(in_channels, hidden_channels, heads=heads)
        # Second GATv2Conv layer (can output final class logits or embeddings)
        self.gatv2_2 = GATv2Conv(hidden_channels * heads, out_channels, heads=1)

    def forward(self, x, edge_index):
        # First GATv2Conv layer
        x = self.gatv2_1(x, edge_index)
        x = torch.relu(x)  # Apply non-linearity
        # Second GATv2Conv layer
        x = self.gatv2_2(x, edge_index)
        return x

# Initialize the model
model = GATv2Model(in_channels=3, hidden_channels=8, out_channels=2, heads=2)  # 3 input features, 8 hidden, 2 output

# Define optimizer and loss function
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = torch.nn.CrossEntropyLoss()

# Example target for node classification (assigning each node a class)
# Assuming the graph has 3 nodes and classes are {0, 1}
target = torch.tensor([0, 1, 0], dtype=torch.long)

# Training loop
for epoch in range(10):  # Train for 10 epochs
    model.train()
    for batch in data_loader:
        # Extract graph data
        x, edge_index = batch.x, batch.edge_index
        
        # Forward pass
        out = model(x, edge_index)
        
        # Compute loss (node classification task)
        loss = loss_fn(out, target)
        
        # Backward pass
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


Epoch 1, Loss: 0.7960
Epoch 2, Loss: 0.7363
Epoch 3, Loss: 0.6873
Epoch 4, Loss: 0.6490
Epoch 5, Loss: 0.6210
Epoch 6, Loss: 0.6003
Epoch 7, Loss: 0.5886
Epoch 8, Loss: 0.5859
Epoch 9, Loss: 0.5895
Epoch 10, Loss: 0.5920


/home/agaru/anaconda3/envs/cvf/lib/python3.12/site-packages/torch_geometric/deprecation.py:26: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch_geometric.nn import GATv2Conv
from torch_geometric.data import DataLoader, Data

# Example data
b = 4  # batch size
N = 3  # number of nodes
e = 5   # number of features

# Create random node features of shape (b, N, e)
node_features = torch.randn(b, N, e)

# Create random adjacency matrix (sparse representation)
# Let's assume a simple fully connected graph for each example in the batch
edge_index = torch.randint(0, N, (2, 10))  # (2, E) edge list

# Create data object for PyG (Graph data)
data = []
for i in range(b):
    data.append(Data(x=node_features[i], edge_index=edge_index))

# Create DataLoader to handle batching
loader = DataLoader(data, batch_size=b, shuffle=True)

# Define the GATv2 model
class GATv2Model(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(GATv2Model, self).__init__()
        self.conv1 = GATv2Conv(in_channels, 8, heads=8)
        self.conv2 = GATv2Conv(8 * 8, out_channels)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = torch.relu(x)
        x = self.conv2(x, edge_index)
        return x

# Initialize model and optimizer
model = GATv2Model(in_channels=e, out_channels=2)  # output 2 features per node
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
for epoch in range(2):
    model.train()
    for batch in loader:
        optimizer.zero_grad()
        print(batch.x, batch.edge_index)
        out = model(batch.x, batch.edge_index)
        # loss = nn.CrossEntropyLoss()(out, batch.y)  # Assuming labels are available in batch.y
        # loss.backward()
        # optimizer.step()
        
    print(f"Epoch {epoch}, Loss: {loss.item()}")


tensor([[-0.9139,  0.6149,  0.9812, -0.5700,  0.3452],
        [ 1.4344,  0.1361, -1.3484,  0.0308, -0.5380],
        [-1.3153,  0.6847,  0.1350, -0.3236, -1.2038],
        [ 0.2109, -0.9298, -2.0815, -0.8336, -0.7837],
        [-0.0216,  0.5454, -1.6100,  0.3000, -1.0913],
        [-1.0150,  0.1497,  0.0090,  0.5826, -0.8983],
        [-0.7432,  1.8359, -0.5978, -0.4964,  0.6323],
        [-0.1667,  0.9800,  0.0780,  0.8520, -1.3966],
        [-1.0770, -1.5055,  1.7758, -0.7520,  0.3057],
        [-0.0598,  1.9505, -0.4992,  0.2236, -1.4574],
        [-1.4815, -0.5764,  0.4616, -0.6324,  0.8536],
        [-0.2653,  0.2413, -0.2854,  0.3065,  2.0186]]) tensor([[ 2,  2,  1,  0,  0,  2,  2,  0,  0,  0,  5,  5,  4,  3,  3,  5,  5,  3,
          3,  3,  8,  8,  7,  6,  6,  8,  8,  6,  6,  6, 11, 11, 10,  9,  9, 11,
         11,  9,  9,  9],
        [ 0,  2,  0,  0,  1,  0,  0,  0,  0,  2,  3,  5,  3,  3,  4,  3,  3,  3,
          3,  5,  6,  8,  6,  6,  7,  6,  6,  6,  6,  8,  9, 11,  9,  