In [29]:
class Singleton(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        new_instance = super(Singleton, cls).__call__(*args, **kwargs)
        if  new_instance not in cls._instances:
            cls._instances[new_instance] = new_instance
        return cls._instances[new_instance]


class ProgramTransitionTreeNode(metaclass=Singleton):

    def __init__(self, indx):
        self.indx = indx
        self.children = []
        self.parents = []

    def add_child(self, child: int):
        self.children.append(child)

    def add_parent(self, parent: int):
        self.parents.append(parent)

    def is_disjoint(self) -> bool:
        return len(self.parents) == 0

    def __hash__(self):
        return hash(self.indx)
    
    def __str__(self):
        return f"{self.__class__.__name__}: {self.indx}"
    
    __repr__ = __str__

In [31]:
pt_node_1 = ProgramTransitionTreeNode(1)
pt_node_1

ProgramTransitionTreeNode: 1

In [19]:
pt_node_1.add_child(10)

In [20]:
pt_node_4 = ProgramTransitionTreeNode(4)

In [21]:
pt_node_4.children

[]

In [22]:
pt_node_1.children

[10]

In [23]:
pt_node_1c = ProgramTransitionTreeNode(1)

In [24]:
pt_node_1.children

[10]

In [25]:
pt_node_4c = ProgramTransitionTreeNode(4)

In [26]:
pt_node_4c.children

[]

In [28]:
pt_node_1

ProgramTransitionTreeNode 1

In [20]:
import torch

In [21]:
l = torch.nn.Conv1d(1, 1, 3)

In [ ]:
x = torch.FloatTensor([
    [[1, 2, 3]],
    [[1, 1, 1]]
])
x, x.shape

(tensor([[[1., 2., 3.]],
 
         [[1., 1., 1.]]]),
 torch.Size([2, 1, 3]))

In [33]:
l(x)

tensor([[[-0.6084]],

        [[-0.2748]]], grad_fn=<ConvolutionBackward0>)

In [34]:
l.weight

Parameter containing:
tensor([[[ 0.1803, -0.1774, -0.0781]]], requires_grad=True)

In [35]:
l.bias

Parameter containing:
tensor([-0.1996], requires_grad=True)