In [1]:
import numpy as np

In [2]:
def y(z, i):
    result = np.exp(z[i]) / np.sum(np.exp(z))
    return result

In [3]:
values = np.zeros((5, 5))
values

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
z = np.array([-3, 1, 100, 5, -1])
z

array([ -3,   1, 100,   5,  -1])

In [5]:
np.exp(-3)/2.688 

0.018521974839235098

In [6]:
0.0185 * (1-0.0185)

0.01815775

In [7]:
np.sum(np.exp(z))

2.6881171418161356e+43

In [ ]:
for i in range(5):
    for j in range(5):
        yi_val = y(z, i)
        print(i, j, yi_val)
        if i == j:
            result = yi_val * (1 - yi_val)
        else:
            yj_val = y(z, j)
            result = - yi_val * yj_val
        values[i, j] = result

In [9]:
values

array([[ 1.85211677e-45, -1.87290028e-88, -1.85211677e-45,
        -1.02256891e-86, -2.53469490e-89],
       [-1.87290028e-88,  1.01122149e-43, -1.01122149e-43,
        -5.58303706e-85, -1.38389653e-87],
       [-1.85211677e-45, -1.01122149e-43,  0.00000000e+00,
        -5.52108228e-42, -1.36853947e-44],
       [-1.02256891e-86, -5.58303706e-85, -5.52108228e-42,
         5.52108228e-42, -7.55581902e-86],
       [-2.53469490e-89, -1.38389653e-87, -1.36853947e-44,
        -7.55581902e-86,  1.36853947e-44]])