In [1]:
import torch

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [3]:
# torch.manual_seed(20)

In [4]:
total_datasize = 100
no_features = 5  # D
no_nodes = 5  # N

In [5]:
syn_data = torch.rand(total_datasize, no_features, no_nodes).to(device)
syn_data[0], syn_data[1]

(tensor([[0.0214, 0.5472, 0.3140, 0.4226, 0.3031],
         [0.3333, 0.5526, 0.6201, 0.1839, 0.1869],
         [0.4734, 0.1056, 0.6813, 0.4370, 0.5189],
         [0.4500, 0.1110, 0.5775, 0.5011, 0.0313],
         [0.7290, 0.2318, 0.6294, 0.7022, 0.2748]], device='cuda:0'),
 tensor([[0.4534, 0.2896, 0.9719, 0.3237, 0.2555],
         [0.0829, 0.5529, 0.3727, 0.5538, 0.7635],
         [0.4027, 0.4069, 0.0454, 0.1118, 0.2520],
         [0.2942, 0.5164, 0.7522, 0.1027, 0.3320],
         [0.8208, 0.5662, 0.0524, 0.9933, 0.0943]], device='cuda:0'))

In [6]:
syn_data = syn_data.reshape(total_datasize, 1, no_features*no_nodes) * torch.randint(0, 2, (total_datasize, 1, no_features*no_nodes)).to(device)
syn_data[0], syn_data[1]

(tensor([[0.0000, 0.5472, 0.3140, 0.4226, 0.0000, 0.0000, 0.5526, 0.6201, 0.0000,
          0.0000, 0.4734, 0.0000, 0.0000, 0.4370, 0.5189, 0.4500, 0.0000, 0.0000,
          0.5011, 0.0000, 0.0000, 0.0000, 0.0000, 0.7022, 0.0000]],
        device='cuda:0'),
 tensor([[0.0000, 0.2896, 0.0000, 0.3237, 0.2555, 0.0829, 0.5529, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.5164, 0.7522,
          0.1027, 0.3320, 0.8208, 0.0000, 0.0524, 0.0000, 0.0000]],
        device='cuda:0'))

In [7]:
import csv

f = open("synthetic_rank_data.csv", "w", newline='')
csv_writer = csv.writer(f)

In [8]:
for i, each_data in enumerate(syn_data):
    distance = torch.round(torch.cdist(syn_data, each_data))
    distance_1d = distance.squeeze(-1).squeeze(-1).detach().cpu().numpy()
    csv_writer.writerow(distance_1d)

f.close()

In [9]:
torch.tensor([1, 2, 3]) * torch.tensor([1, 2, 3])

tensor([1, 4, 9])

In [16]:
syn_data = torch.rand(1, 3)
syn_data

tensor([[0.6156, 0.2713, 0.4532]])

In [80]:
def distance(x, y):
    return torch.sum(y - x)

In [81]:
def get_embedding_at_distance_1(tensor1):
    tensor2 = torch.rand(tensor1.shape)
    desired_distance = 1
    initial_distance = distance(tensor1, tensor2)
    scale_factor = desired_distance / initial_distance
    tensor2 = tensor1 + (tensor2 - tensor1) * scale_factor
    return tensor2

In [96]:
syn_data = torch.rand((1, 5))
syn_data

tensor([[0.7334, 0.7971, 0.5669, 0.8613, 0.9027]])

In [97]:
syn_data2 = get_embedding_at_distance_1(syn_data)
syn_data2

tensor([[0.7752, 0.9485, 0.6441, 1.4947, 0.9987]])

In [98]:
distance(syn_data, syn_data2)

tensor(1.)

In [99]:
syn_data3 = get_embedding_at_distance_1(syn_data2)
syn_data3

tensor([[1.0613, 1.2425, 0.5389, 1.8651, 1.1536]])

In [100]:
distance(syn_data2, syn_data3)

tensor(1.)

In [101]:
distance(syn_data, syn_data3)

tensor(2.)

In [102]:
syn_data12 = get_embedding_at_distance_1(syn_data)
syn_data12

tensor([[1.0041, 0.6622, 0.8786, 0.8008, 1.5158]])

In [103]:
distance(syn_data12, syn_data3)

tensor(1.0000)