In [1]:
import pickle

import torch

import torch.nn as nn

In [2]:
N = 256
D = 4

In [3]:
embedding = nn.Embedding(N, D)

In [4]:
def custom_loss(output, target, target_mask):
    distance = torch.zeros((N, N))
    for r in range(N):
        for c in range(N):
            distance[r, c] = torch.cdist(output[r].unsqueeze(0), output[c].unsqueeze(0))

    loss = torch.mean(torch.square(target - distance))
    return loss

In [5]:
hd = 0

In [6]:
# target = torch.FloatTensor([[0, 0, 1, 1], [0, 0, 1, 2], [0, 0, 0, 1], [0, 0, 0, 0]])
# target = [
#     [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#     [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
#     [1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
#     [0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
#     [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#     [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0],
#     [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0],
#     [0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#     [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#     [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
#     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
# ]

target = pickle.load(open("matrix3.dump", "rb"))
target = torch.FloatTensor(target)

In [7]:
target_mask = target == hd
# target_mask

In [8]:
# target.masked_fill(target_mask, 0)

In [9]:
optimizer = torch.optim.Adam(embedding.parameters(), lr=0.01, weight_decay=0.01)

In [10]:
# loss = torch.nn.CosineEmbeddingLoss()

In [11]:
def train(epoch):
    optimizer.zero_grad()
    loss = custom_loss(embedding.weight, target, target_mask)
    loss.backward()
    optimizer.step()
    print("Epoch:", epoch, "| Loss:", loss)

In [12]:
for i in range(500):
    train(i)

Epoch: 0 | Loss: tensor(8.2941, grad_fn=<MeanBackward0>)
Epoch: 1 | Loss: tensor(8.1671, grad_fn=<MeanBackward0>)
Epoch: 2 | Loss: tensor(8.0419, grad_fn=<MeanBackward0>)
Epoch: 3 | Loss: tensor(7.9182, grad_fn=<MeanBackward0>)
Epoch: 4 | Loss: tensor(7.7962, grad_fn=<MeanBackward0>)
Epoch: 5 | Loss: tensor(7.6758, grad_fn=<MeanBackward0>)
Epoch: 6 | Loss: tensor(7.5571, grad_fn=<MeanBackward0>)
Epoch: 7 | Loss: tensor(7.4400, grad_fn=<MeanBackward0>)
Epoch: 8 | Loss: tensor(7.3245, grad_fn=<MeanBackward0>)
Epoch: 9 | Loss: tensor(7.2107, grad_fn=<MeanBackward0>)
Epoch: 10 | Loss: tensor(7.0985, grad_fn=<MeanBackward0>)
Epoch: 11 | Loss: tensor(6.9880, grad_fn=<MeanBackward0>)
Epoch: 12 | Loss: tensor(6.8791, grad_fn=<MeanBackward0>)
Epoch: 13 | Loss: tensor(6.7718, grad_fn=<MeanBackward0>)
Epoch: 14 | Loss: tensor(6.6660, grad_fn=<MeanBackward0>)
Epoch: 15 | Loss: tensor(6.5619, grad_fn=<MeanBackward0>)
Epoch: 16 | Loss: tensor(6.4594, grad_fn=<MeanBackward0>)
Epoch: 17 | Loss: tensor

In [30]:
embed = embedding(torch.LongTensor([1, 33]))
torch.cdist(embed[0].unsqueeze(0), embed[1].unsqueeze(0))

tensor([[0.0142]], grad_fn=<CdistBackward0>)

In [14]:
embedding.weight

Parameter containing:
tensor([[ 0.0006, -0.0027, -0.0002,  0.0339],
        [-0.0005, -0.0047,  0.0046,  0.0013],
        [ 0.0048, -0.0040,  0.0106,  0.0042],
        ...,
        [-0.0330, -0.0006,  0.0033,  0.0026],
        [ 0.0060, -0.0061,  0.0051,  0.0023],
        [ 0.0026, -0.0093,  0.0064,  0.0060]], requires_grad=True)

In [28]:
(target[1]).nonzero()

tensor([[  0],
        [  9],
        [ 33],
        [129]])

In [31]:
pickle.dump(embedding.weight.detach().cpu(), open("embedding.dump", "wb"))

In [32]:
import pickle

wt = pickle.load(open("embedding.dump", "rb"))

In [34]:
wt.shape

torch.Size([256, 4])