In [2]:
import torch

import torch.nn as nn

In [11]:
transformer_model = nn.Transformer(d_model=2, nhead=1, num_encoder_layers=12)
src = torch.rand((1, 1, 2))
tgt = torch.rand((1, 1, 2))
out = transformer_model(src, tgt)

/home/agaru/anaconda3/envs/cvf/lib/python3.12/site-packages/torch/nn/modules/transformer.py:379: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(


In [12]:
out

tensor([[[-1.0000,  1.0000]]], grad_fn=<NativeLayerNormBackward0>)

In [13]:
loss = torch.nn.MSELoss()

In [14]:
loss(out, tgt)

tensor(2.1452, grad_fn=<MseLossBackward0>)

In [15]:
src

tensor([[[0.7469, 0.0753]]])

In [16]:
tgt

tensor([[[0.8261, 0.0223]]])

In [4]:
torch.empty(4)

tensor([7.6406e+20, 3.5237e-41, 1.0842e-19, 2.9661e-04])