In [5]:

import torch
from torch_geometric.nn import Node2Vec

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device


'cuda'

In [ ]:
import os
import json

dataset_dir = os.path.join(
    os.getenv("CVF_PROJECT_DIR", ""), "cvf-analysis", "v2", "datasets", "coloring"
)
edge_index_file = "graph_7_edge_index.json"

# edge_index = torch.tensor(
#     json.load(open(os.path.join(dataset_dir, edge_index_file), "r")),
#     dtype=torch.long,
# )
edge_index = (
            torch.tensor(
                json.load(open(os.path.join(dataset_dir, edge_index_file), "r")),
                dtype=torch.long,
            )
            .t()
            .to(device)
        )

In [ ]:
model = Node2Vec(
    edge_index,
    embedding_dim=1,
    walks_per_node=10,
    walk_length=5,
    context_size=10,
    p=1.0,
    q=1.0,
    num_negative_samples=1,
).to(device)

# optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [25]:
edge_index

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 6, 6, 7, 7, 8, 8, 9, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 5, 0, 5, 0, 5, 0, 5, 0, 1, 2, 3, 4, 6, 7,
         8, 9, 0, 5, 0, 5, 0, 5, 0, 5]], device='cuda:0')

In [26]:
model

Node2Vec(10, 2)

In [27]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [28]:
model

Node2Vec(10, 2)

In [29]:
loader = model.loader(batch_size=128, shuffle=True, num_workers=4)

In [30]:
pos_rw, neg_rw = next(iter(loader))
pos_rw, neg_rw

(tensor([[1, 5, 4,  ..., 0, 4, 0],
         [4, 0, 8,  ..., 9, 0, 2],
         [7, 0, 6,  ..., 5, 9, 5],
         ...,
         [5, 2, 0,  ..., 6, 5, 0],
         [5, 2, 5,  ..., 4, 0, 9],
         [0, 6, 0,  ..., 1, 0, 6]]),
 tensor([[1, 9, 2,  ..., 3, 4, 7],
         [4, 1, 6,  ..., 4, 3, 2],
         [7, 0, 0,  ..., 1, 6, 5],
         ...,
         [7, 2, 9,  ..., 0, 7, 1],
         [4, 5, 2,  ..., 8, 7, 4],
         [6, 0, 4,  ..., 5, 0, 9]]))

In [31]:
pos_rw.shape, neg_rw.shape

(torch.Size([1100, 10]), torch.Size([1100, 10]))